// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package surveys

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// InsertSurvey insert new survey record
	InsertSurvey(ctx context.Context, arg InsertSurveyParams) (SurveysEav, error)
	// InsertSurveyAttribute
	InsertSurveyAttribute(ctx context.Context, arg InsertSurveyAttributeParams) (SurveyAttribute, error)
	// InsertSurveyValue insert new survey value record
	InsertSurveyValue(ctx context.Context, arg InsertSurveyValueParams) (SurveyValue, error)
	// ListSurbeyAttributes
	ListSurveyAttributes(ctx context.Context, surveyID uuid.UUID) ([]ListSurveyAttributesRow, error)
	// ListSurveys retrieve partial survey records
	ListSurveys(ctx context.Context, arg ListSurveysParams) ([]ListSurveysRow, error)
	// ReadSurvey by id
	ReadSurvey(ctx context.Context, id uuid.UUID) (SurveysEav, error)
}

var _ Querier = (*Queries)(nil)
