// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package assessments

import (
	"context"
)

type Querier interface {
	// InsertAssessmentValue create new assessment value
	InsertAssessmentValue(ctx context.Context, arg InsertAssessmentValueParams) (AssessmentValue, error)
	// ReadAssessmentAttribute by id
	ReadAssessmentAttribute(ctx context.Context, arg ReadAssessmentAttributeParams) (AssessmentAttribute, error)
}

var _ Querier = (*Queries)(nil)
